version: '3'
services:
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '5173:5173'
  server:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: itransition
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sinitsa